apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwg-de-api-server
  namespace: nwg-de
  labels:
    app: nwg-de-api-server
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nwg-de-api-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "nwg-de-role"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-config: "internal/data/nwg-de"
        vault.hashicorp.com/secret-volume-path: "/app"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "internal/data/nwg-de" -}}
          {{- .Data | toJSONPretty }}
          {{- end }}
      labels:
        app: nwg-de-api-server
        namespace: nwg-de
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: nwg-de-api-server
          image: registry.johnpillar.me/nwg-de-api-server:0.0.1 # {"$imagepolicy": "flux-system:nwg-de-api-server"}
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: GIN_MODE
              value: "release"
          resources:
            limits:
              memory: "40Mi"
              cpu: "0.2"
            requests:
              memory: "20Mi"
              cpu: "0.1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
      imagePullSecrets:
        - name: private-repo
      nodeSelector:
        storage: no
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nwg-de-api-server
              topologyKey: "kubernetes.io/hostname"
