name: Go

env:
  MAJOR_VER: 0
  MINOR_VER: 1

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Setup private repo access
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: JOHNEPPILLAR
          password: ${{ secrets.REPO_ACCESS }}

      - name: Build
        run: go build -v ./...

      - name: Slack Notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: github_builds
          SLACK_USERNAME: "Github CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars2.githubusercontent.com/u/25100863?s=40&v=4
          SLACK_TITLE: "CI failed - (Go) NWG-DE - API Server"
          SLACK_MESSAGE: "Build failed  :bangbang:"
          SLACK_COLOR: "#ff0000"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS }}

      - name: Login to private registery
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTERY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag repo code
        if: success()
        run: git tag v${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}

      - name: Build docker container
        if: success()
        run: docker build --build-arg GO_PRIVATE_REPO_KEY=${{ secrets.REPO_ACCESS }} . -t ${{ secrets.DOCKER_REGISTERY_URL }}/nwg-de-api-server:${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}

      - name: Push docker container to private registery
        if: success()
        run: docker push ${{ secrets.DOCKER_REGISTERY_URL }}/nwg-de-api-server:${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}

      - name: Push new tag
        if: success()
        run: git push origin v${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}

      - name: Slack Notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: github_builds
          SLACK_USERNAME: "Github CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars2.githubusercontent.com/u/25100863?s=40&v=4
          SLACK_TITLE: "CD failed - (Go) NWG-DE - API Server"
          SLACK_MESSAGE: "Deploy failed  :bangbang:"
          SLACK_COLOR: "#ff0000"
